# Generated by Django 5.2 on 2025-04-21 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='userRole',
            field=models.CharField(blank=True, choices=[('engineer', 'Engineer'), ('leader', 'Team Leader'), ('dept_leader', 'Department Leader'), ('senior_manager', 'Senior Manager')], max_length=30, null=True),
        ),
    ]
