# Generated by Django 5.2 on 2025-04-24 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_customuser_delete_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='userTeam',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
