# Generated by Django 5.2 on 2025-04-25 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_customuser_userteam'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='userTeam',
            field=models.CharField(blank=True, choices=[('team1', 'Team 1'), ('team2', 'Team 2'), ('team3', 'Team 3')], max_length=50, null=True),
        ),
    ]
