

# Generated by Django 5.1.7 on 2025-04-17 18:59

import django.db.models.deletion
from django.db import migrations, models
from django.conf import settings


class Migration(migrations.Migration):

    initial = True

    dependencies = [

        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(

            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_date', models.DateField()),
                ('session_time', models.TimeField()),
                ('session_completed', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='HealthCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hc_question', models.CharField(max_length=500)),
                ('hc_hint_red', models.CharField(max_length=500)),
                ('hc_hint_green', models.CharField(max_length=500)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='voting.session')),
            ],

        ),
    ]
